import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedComponent9Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedEQUIPOWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedArrowbackcircleWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedIntegrantesdelaligaWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedTornadosVerdesWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedEquipoenjuegocompetitivoWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedequipowidget1/generated/GeneratedRectangle17Widget1.dart';

/* Frame Equipo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEquipoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 104.0,
                child: GeneratedComponent4Widget(),
              ),
              Positioned(
                left: -32.0,
                top: -12.0,
                right: null,
                bottom: null,
                width: 446.0,
                height: 130.49441528320312,
                child: GeneratedComponent9Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 36.0,
                child: GeneratedEQUIPOWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 31.0,
                child: GeneratedIntegrantesdelaligaWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 43.0,
                child: GeneratedTornadosVerdesWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 43.0,
                child: GeneratedEquipoenjuegocompetitivoWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 171.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 137.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 701.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 39.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 71.524169921875,
                top: 702.5297241210938,
                right: null,
                bottom: null,
                width: 39.0,
                height: 48.0,
                child: GeneratedArrowbackcircleWidget(),
              )
            ]),
      ),
    ));
  }
}
