import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomponent1widget/generated/GeneratedEquipoWidget9.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomponent1widget/generated/GeneratedBagchecksharpWidget6.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomponent1widget/generated/GeneratedPersoncircleoutlineWidget6.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomponent1widget/generated/GeneratedPerfilWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomponent1widget/generated/GeneratedRoldejuegoWidget8.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomponent1widget/generated/GeneratedSeleccionWidget7.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomponent1widget/generated/GeneratedRectangle5Widget6.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomponent1widget/generated/GeneratedPeopleWidget6.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedcomponent1widget/generated/GeneratedFootballWidget6.dart';

/* Component Component 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponent1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 104.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle5Widget6(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.178743961352657;

                final double height =
                    constraints.maxHeight * 0.21153846153846154;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.06280193236714976,
                      y: constraints.maxHeight * 0.7307692307692307,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPerfilWidget7(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.17149758454106281;

                final double height =
                    constraints.maxHeight * 0.18269230769230768;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.28743961352657005,
                      y: constraints.maxHeight * 0.7307692307692307,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRoldejuegoWidget8(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.178743961352657;

                final double height =
                    constraints.maxHeight * 0.21153846153846154;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.5193236714975845,
                      y: constraints.maxHeight * 0.75,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedSeleccionWidget7(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.178743961352657;

                final double height =
                    constraints.maxHeight * 0.21153846153846154;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.7439613526570048,
                      y: constraints.maxHeight * 0.75,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedEquipoWidget9(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.16666666666666666;

                final double height =
                    constraints.maxHeight * 0.6057692307692307;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.06280193236714976,
                      y: constraints.maxHeight * 0.125,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPersoncircleoutlineWidget6(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.18115942028985507;

                final double height =
                    constraints.maxHeight * 0.6634615384615384;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.2632850241545894,
                      y: constraints.maxHeight * 0.0673076923076923,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedFootballWidget6(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.16183574879227053;

                final double height =
                    constraints.maxHeight * 0.6346153846153846;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.5,
                      y: constraints.maxHeight * 0.0673076923076923,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedBagchecksharpWidget6(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.19082125603864733;

                final double height = constraints.maxHeight * 0.625;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.717391304347826,
                      y: constraints.maxHeight * 0.125,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPeopleWidget6(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
