import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedExitWidget6.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedSEDESCARGARAELFORMATODELAJUGADAWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedComponent10Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedRolesdejuegoWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedGroup5Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedComponent5Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget5/generated/GeneratedNOTAWidget1.dart';

/* Frame Rol de juego
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRoldejuegoWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 104.0,
                child: GeneratedComponent5Widget1(),
              ),
              Positioned(
                left: -32.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 446.0,
                height: 130.49441528320312,
                child: GeneratedComponent10Widget1(),
              ),
              Positioned(
                left: 43.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 43.0,
                child: GeneratedRolesdejuegoWidget1(),
              ),
              Positioned(
                left: 65.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 485.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 141.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 24.0,
                child: GeneratedGroup5Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 173.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 134.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 70.0,
                child: GeneratedSEDESCARGARAELFORMATODELAJUGADAWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 43.0,
                child: GeneratedNOTAWidget1(),
              ),
              Positioned(
                left: 343.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 49.0,
                child: GeneratedExitWidget6(),
              )
            ]),
      ),
    ));
  }
}
