import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget3/generated/GeneratedComponent5Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget3/generated/GeneratedRolesdejuegoWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget3/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget3/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedroldejuegowidget3/generated/GeneratedComponent10Widget.dart';

/* Frame Rol de juego
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRoldejuegoWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 104.0,
                child: GeneratedComponent5Widget(),
              ),
              Positioned(
                left: -32.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 446.0,
                height: 130.49441528320312,
                child: GeneratedComponent10Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 43.0,
                child: GeneratedRolesdejuegoWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 485.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 141.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 24.0,
                child: GeneratedGroup5Widget(),
              )
            ]),
      ),
    ));
  }
}
