import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget/generated/GeneratedESCRIBEAQUIENTUJUEGOWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget/generated/GeneratedESCRIBEAQUITUNUMERODEJUGADORWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget/generated/GeneratedSquigglesColorfulWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget/generated/GeneratedRectangle1Widget.dart';

/* Frame Pagina principal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaginaprincipalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 465.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: -250.0,
                top: -28.0,
                right: null,
                bottom: null,
                width: 915.0,
                height: 575.0,
                child: GeneratedSquigglesColorfulWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 448.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 88.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 88.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 27.0,
                child: GeneratedESCRIBEAQUIENTUJUEGOWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 27.0,
                child: GeneratedESCRIBEAQUITUNUMERODEJUGADORWidget(),
              ),
              Positioned(
                left: 108.0,
                top: 798.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 45.0,
                child: GeneratedGroup3Widget(),
              )
            ]),
      ),
    ));
  }
}
