import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedNOTAWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedESCRIBEAQUIENTUJUEGOWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedSesalioselasesionWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedESCRIBEAQUITUNUMERODEJUGADORWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedSquigglesColorfulWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedpaginaprincipalwidget1/generated/GeneratedRectangle17Widget.dart';

/* Frame Pagina principal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaginaprincipalWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 465.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: -250.0,
                top: -28.0,
                right: null,
                bottom: null,
                width: 915.0,
                height: 575.0,
                child: GeneratedSquigglesColorfulWidget1(),
              ),
              Positioned(
                left: 2.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 448.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 36.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 88.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 36.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 88.0,
                child: GeneratedGroup2Widget1(),
              ),
              Positioned(
                left: 51.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 27.0,
                child: GeneratedESCRIBEAQUIENTUJUEGOWidget1(),
              ),
              Positioned(
                left: 49.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 27.0,
                child: GeneratedESCRIBEAQUITUNUMERODEJUGADORWidget1(),
              ),
              Positioned(
                left: 108.0,
                top: 798.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 45.0,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 136.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 95.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 31.0,
                child: GeneratedSesalioselasesionWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 43.0,
                child: GeneratedNOTAWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08876665087713712;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      36.749393463134766;

                  double percentHeight = 0.03759765625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 33.6875;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7971014492753623,
                        translateY: constraints.maxHeight * 0.4575892857142857,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
