import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent15Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent2Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent12Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent17Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent7Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent13Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent19Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent18Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent16Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedTOPDEMEJORESSELECCIONESDEFUTBOLWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedseleccionwidget/generated/GeneratedComponent14Widget.dart';

/* Frame Seleccion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSeleccionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 104.0,
                child: GeneratedComponent2Widget(),
              ),
              Positioned(
                left: -32.0,
                top: -13.0,
                right: null,
                bottom: null,
                width: 446.0,
                height: 130.49441528320312,
                child: GeneratedComponent7Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 161.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 220.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 158.0,
                child: GeneratedTOPDEMEJORESSELECCIONESDEFUTBOLWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 46.0,
                child: GeneratedComponent12Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 46.0,
                child: GeneratedComponent13Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 46.0,
                child: GeneratedComponent14Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 46.0,
                child: GeneratedComponent15Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 46.0,
                child: GeneratedComponent16Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 46.0,
                child: GeneratedComponent17Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 46.0,
                child: GeneratedComponent18Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 716.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 46.0,
                child: GeneratedComponent19Widget(),
              )
            ]),
      ),
    ));
  }
}
