import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedComponent8Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/Generated14Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedEquipoWidget8.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedDiasdeentrenamientoWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedEntrenadorWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedSaulLopezPerezWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedLunesMiercolesViernesSabadoWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedPosicionWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedNumerodejugadorWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedTornadosverdesWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedRaulTorresSerranoWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedMediapuntaWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedNombreWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedVerplanesdejuegoWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedperfilwidget5/generated/GeneratedComponent3Widget.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 104.0,
                child: GeneratedComponent3Widget(),
              ),
              Positioned(
                left: -33.0,
                top: -14.0,
                right: null,
                bottom: null,
                width: 446.0,
                height: 130.49441528320312,
                child: GeneratedComponent8Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 128.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 37.0,
                child: GeneratedNombreWidget(),
              ),
              Positioned(
                left: 147.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 34.0,
                child: GeneratedRaulTorresSerranoWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 35.0,
                child: GeneratedDiasdeentrenamientoWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 34.0,
                child: GeneratedLunesMiercolesViernesSabadoWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 37.0,
                child: GeneratedPosicionWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 34.0,
                child: GeneratedMediapuntaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 34.0,
                child: GeneratedNumerodejugadorWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 37.0,
                child: Generated14Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 37.0,
                child: GeneratedEquipoWidget8(),
              ),
              Positioned(
                left: 147.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 34.0,
                child: GeneratedTornadosverdesWidget(),
              ),
              Positioned(
                left: 246.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 195.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 101.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 207.00241088867188,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 34.0,
                child: GeneratedVerplanesdejuegoWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 37.0,
                child: GeneratedEntrenadorWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 34.0,
                child: GeneratedSaulLopezPerezWidget(),
              )
            ]),
      ),
    ));
  }
}
